# Generated by Django 5.1.4 on 2026-02-26 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='gigs.gig'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
    ]
