# Generated by Django 5.1.4 on 2026-02-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_platform_fee_order_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub repository link for the project', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='submission_file',
            field=models.FileField(blank=True, help_text='PDF file for delivery', null=True, upload_to='submissions/'),
        ),
        migrations.AddField(
            model_name='order',
            name='submission_note',
            field=models.TextField(blank=True, help_text='Additional notes from the seller'),
        ),
    ]
