# Generated by Django 5.1.4 on 2026-02-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_gigs',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='gigs.gig'),
        ),
    ]
