# Generated by Django 5.1.4 on 2026-02-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_saved_gigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect Account ID', max_length=100),
        ),
    ]
